development:
  adapter: postgresql
  encoding: UTF-8
  username: driverproject
  password: password123qwe
  database: database_driver_dev
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: database-driver-test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ENV['DATABASE_URL']
  pool: 5
  timeout: 5000
